version: '3.8'
services:
    mongodb:
      #image: mongodb/mongodb-community-server:4.4.8-ubuntu2004
      image: mongo:7-jammy
      #restart: always
      ports:
        - '27017:27017'
      volumes: 
        - mongodb:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  mongodb: